spring:
  datasource:
    url: jdbc:mysql://124.71.141.149:3306/follow_coin?characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root@123
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    mode: HTML5
server:
  servlet:
    context-path: /follow
  port: 8090
mybatis:
  type-aliases-package: com.monkey.follow.model
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: system.log