spring:
  datasource:
    url: jdbc:mysql://101.132.157.222:3306/coin?characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

mybatis:
  type-aliases-package: com.monkey.follow.model
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: system.log

server:
  servlet:
    context-path: /follow
  port: 8090

okex:
  config: true